# Generated by Django 5.0.6 on 2024-06-17 14:25

import django_resized.forms
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='images/chat/avatar/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
    ]
