# Generated by Django 5.0.6 on 2024-05-24 08:58

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
    ]
