# Generated by Django 5.0.6 on 2024-05-24 09:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
    ]
