# Generated by Django 5.0.6 on 2024-05-27 05:18

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chat_type_chat_type_alter_chat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/chat/avatar/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
    ]
