# Generated by Django 5.0.6 on 2024-05-29 06:41

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_owner_alter_chat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlechatmessage',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/chat/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
    ]
